import type {Point} from '../lib/indicators';
type Cost={period:string;annual:number|null;since2019:number|null};
type Pay=Cost&{wageAnnual:number|null;costAnnual:number|null;wageSince2019:number|null;costSince2019:number|null};
export type WorkerData={pay:Pay|null;rent:Cost|null;mortgage:Cost|null;underemployment:{period:string;rate:number;annualChange:number|null}|null;output:Cost|null};
export type WorkerSources={wages:string;costs:string;rent:string;underemployment:string;gdp:string};
const signed=(v:number|null|undefined,unit='%')=>v==null?'Unavailable':`${v>0?'+':''}${v.toFixed(2)}${unit}`;
const period=(p?:string)=>!p?'Awaiting data':p.includes('Q')?`${p.split('-')[1]} ${p.slice(0,4)}`:new Date(`${p}-01`).toLocaleDateString('en-AU',{month:'short',year:'numeric',timeZone:'UTC'});
const direction=(n:number|null|undefined,reverse=false)=>n==null?'Unknown':Math.abs(n)<1e-9?'Unchanged':(n>0)!==reverse?'Improving':'Worsening';
function Trend({value,reverse=false}:{value:number|null|undefined;reverse?:boolean}){const d=direction(value,reverse);return <span className={`trend ${d.toLowerCase()}`}>{d}</span>;}
function Source({url,name}:{url?:string;name:string}){return url?<a href={url} target="_blank" rel="noreferrer">{name} ↗</a>:null;}
export default function WorkerPanel({data,sources,perCapitaGrowth,loading}:{data:WorkerData|undefined;sources:WorkerSources|undefined;perCapitaGrowth:Point[];loading:boolean}){
 const pay=data?.pay,under=data?.underemployment;
 const signals=[pay?.annual,data?.rent?.annual==null?null:-data.rent.annual,data?.mortgage?.annual==null?null:-data.mortgage.annual,under?.annualChange==null?null:-under.annualChange];
 const known=signals.filter((n):n is number=>n!=null);
 const summary=!known.length?(loading?'Checking household pressures…':'Household pressures: data unavailable'):known.some(n=>n<0)&&known.some(n=>n>0)?'A mixed picture for working households.':known.some(n=>n<0)?'Working households are still under pressure.':known.some(n=>n>0)?'The measured pressures are easing.':'The measured pressures are unchanged.';
 return <section className="workerPanel" aria-labelledby="worker-heading"><div className="workerIntro"><span className="eyebrow">THE HOUSEHOLD PICTURE</span><h2 id="worker-heading">Are working people getting ahead?</h2><p className="workerSummary">{summary}</p><p>Australia can avoid a technical recession while pay buys less, housing costs rise, or people cannot get enough paid work. These are measures of everyday pressure, not additional recession tests.</p></div><div className="workerGrid">
 <article className="workerCard"><div className="cardTop"><span className="eyebrow">PAY & PURCHASING POWER</span><Trend value={pay?.annual}/></div><h3>Does your pay buy more?</h3><div className="workerNumber">{signed(pay?.annual)}</div><p className="metricCaption">Change in wage purchasing power over one year · {period(pay?.period)}</p><div className="comparison"><span>Hourly wages</span><strong>{signed(pay?.wageAnnual)}</strong><span>Employee living costs</span><strong>{signed(pay?.costAnnual)}</strong></div><div className="longTerm"><span>SINCE Q4 2019</span><strong>{signed(pay?.since2019)} purchasing power</strong><p>{pay?.since2019==null?'The longer-term comparison is unavailable.':pay.since2019<0?(pay.annual!=null&&pay.annual>0?'Wages are catching up lately, but this measure remains below its pre-pandemic level.':'Hourly wages have not kept pace with employee household living costs since Q4 2019.'):'This measure is at or above its pre-pandemic level; that does not describe every worker.'}</p></div><p className="cardExplanation">Compares hourly wage rates with the employee household living-cost index. It is a before-tax benchmark, not your take-home pay; promotions, hours and individual expenses can differ.</p><div className="cardSources"><Source url={sources?.wages} name="ABS wages"/><Source url={sources?.costs} name="ABS living costs"/></div></article>
 <article className="workerCard"><div className="cardTop"><span className="eyebrow">HOUSING</span><span className="tag">Renters & borrowers</span></div><h3>Is housing getting more expensive?</h3><div className="housingMetric"><div><span>Rents · one year</span><strong>{signed(data?.rent?.annual)}</strong><small>{period(data?.rent?.period)}</small></div><Trend value={data?.rent?.annual} reverse/></div><div className="housingMetric"><div><span>Mortgage interest costs · one year</span><strong>{signed(data?.mortgage?.annual)}</strong><small>{period(data?.mortgage?.period)}</small></div><Trend value={data?.mortgage?.annual} reverse/></div><div className="longTerm"><span>SINCE Q4 2019</span><strong>Rents {signed(data?.rent?.since2019)}</strong><strong>Mortgage interest {signed(data?.mortgage?.since2019)}</strong></div><p className="cardExplanation">These are cost changes, not the share of income spent on housing. The rent index covers existing and new tenancies across capital cities. Mortgage interest excludes principal repayments and does not represent every borrower’s bill.</p><div className="cardSources"><Source url={sources?.rent} name="ABS rents"/><Source url={sources?.costs} name="ABS mortgage costs"/></div></article>
 <article className="workerCard"><div className="cardTop"><span className="eyebrow">ENOUGH PAID WORK</span><Trend value={under?.annualChange} reverse/></div><h3>Can people get enough hours?</h3><div className="workerNumber">{under?`${under.rate.toFixed(2)}%`:'Unavailable'}</div><p className="metricCaption">Underemployment rate · {period(under?.period)}</p><div className="longTerm"><span>CHANGE OVER ONE YEAR</span><strong>{signed(under?.annualChange,' pp')}</strong><p>{under?.annualChange==null?'The annual comparison is unavailable.':under.annualChange>0?'A larger share of the labour force is underemployed than a year ago.':under.annualChange<0?'A smaller share is underemployed than a year ago.':'The share is unchanged from a year ago.'}</p></div><p className="cardExplanation">The headline ABS measure includes part-time workers who want and are available for more hours, and full-time workers on reduced hours for economic reasons. Having a job does not always mean having enough paid work.</p><div className="cardSources"><Source url={sources?.underemployment} name="ABS underemployment"/></div></article>
 <article className="workerCard"><div className="cardTop"><span className="eyebrow">GROWTH PER PERSON</span><Trend value={data?.output?.annual}/></div><h3>Is output per person growing?</h3><div className="workerNumber">{signed(data?.output?.annual)}</div><p className="metricCaption">Real GDP per person · one year · {period(data?.output?.period)}</p><div className="comparison"><span>Latest quarter</span><strong>{signed(perCapitaGrowth.at(-1)?.value)}</strong></div><div className="longTerm"><span>SINCE Q4 2019</span><strong>{signed(data?.output?.since2019)} output per person</strong></div><p className="cardExplanation">Total GDP can grow partly because there are more people. Output per person helps separate those effects, but it is not a measure of wages, household income or who receives the gains.</p><div className="cardSources"><Source url={sources?.gdp} name="ABS national accounts"/></div></article>
 </div><div className="explainers"><div><h3>Slower inflation ≠ cheaper groceries</h3><p>Lower inflation means prices are rising more slowly. Prices fall only when their rate of change is negative. A smaller annual increase can still leave bills far above 2019 levels.</p></div><div><h3>One average, different experiences</h3><p>Renters, mortgage holders and people who own their home outright face different costs. Your pay, hours, family needs and location can move differently from these averages.</p></div></div><p className="workerFootnote">“Improving” and “worsening” compare the latest year: purchasing power and output rising, housing costs falling, or underemployment falling. They do not establish affordability or financial comfort. Missing or stale readings are unknown.</p></section>;
}
